# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts

    working_directory: ~/simple-vue-app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - simple-vue-app-dep-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - simple-vue-app-dep-

      - run: 
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: simple-vue-app-dep-{{ checksum "package.json" }}

      # Run tests!
      - run: 
          name: Run unit tests
          command: yarn test:unit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master