# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:lts

commands:
  app-build: 
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - simple-vue-app-dep-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - simple-vue-app-dep-

      - run: 
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: simple-vue-app-dep-{{ checksum "package.json" }}
      
jobs:
  build:
    executor: node-executor
    working_directory: ~/simple-vue-app
    steps:
      - app-build

  test:
    executor: node-executor
    working_directory: ~/simple-vue-app
    steps:
      - app-build
      - run: 
          name: Run unit tests
          command: yarn test:unit

  deploy:
    executor: node-executor
    working_directory: ~/simple-vue-app
    steps:
      - app-build
      - restore_cache:
          keys:
            - vue-app-dist-cache-{{ .Branch }}
      - run:
          name: App Build
          command: yarn build
      - save_cache:
          key: vue-app-dist-cache-{{ .Branch }}
          paths:
            - ./dist
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir=dist -p

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master